name: wash_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.0
  go_router: ^11.1.2
  dio: ^5.3.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  mobile_scanner: ^3.5.0
  path_provider: ^2.1.1
  equatable: ^2.0.5
  get_it: ^7.6.4
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: ^7.0.0
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.0.0
  json_serializable: ^6.7.0
  

flutter:

  uses-material-design: true

 
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
